name: Cleanup Packages
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 1 * * sun'

permissions:
  contents: read
  packages: write
  deployments: write

jobs:
  package_cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v5
        with:
          package-name: 'wordpress-container'
          package-type: container
          min-versions-to-keep: 14
